export default {
  light: {
    text: "#1A1A2E",
    textSecondary: "#6B7280",
    background: "#FFF5F0",
    surface: "#FFFFFF",
    tint: "#FF6B9D",
    accent: "#C44DFF",
    mint: "#4ECDC4",
    coral: "#FF6B6B",
    yellow: "#FFE66D",
    tabIconDefault: "#9CA3AF",
    tabIconSelected: "#FF6B9D",
    border: "#F0E6E0",
    cardShadow: "rgba(255, 107, 157, 0.08)",
    categoryMeals: "#FF6B6B",
    categorySnacks: "#FFB347",
    categoryItems: "#4ECDC4",
    categoryAccessories: "#C44DFF",
    categoryFurniture: "#FF6B9D",
    categoryLivings: "#45B7D1",
    categorySpecial: "#FFE66D",
  },
};
